### PR TITLE
fix(cards)!: fixed positioning of image inside cards of carousel 

### LINKED ISSUE #161: bug: carousel images look warped in mobile devices
### Describe the bug

image

### To reproduce

Visit https://atlas.ourkolkata.in

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by GeeekySouro003**
Closes #161 

## Checklist

- [x] I have followed every step in the [contributing guide](https://github.com/Pujo-Atlas-Kolkata/PujoAtlasKol-Web/blob/dev/CONTRIBUTING.md)
- [x] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I performed a functional test on my final commit

---

## Changelog

Changed the problem of image being wrapped in mobile view just alter some dimensions of image tag in cards section

---

## Screenshots

image

### CODE REVIEW

**Review by Heisen47 — APPROVED** [review]
LGTM

**Comment by Heisen47** [comment]
hi , have you joined our discord server? if yes can you provide your discord username . To work on any issue you need to be assigned to it first . 

assignment is done via discord server

**Comment by GeeekySouro003** [comment]
i cant join the discord server as it shows me unable to accept invite

image

**Comment by Heisen47** [comment]
https://discord.gg/3Rta2h5h 

this is the link. 

give me your userID i can invite you too

**Review by AyanavaKarmakar — CHANGES_REQUESTED** [review]
ref: https://discord.com/channels/1166382233880383519/1278043206948491305/1292567027130699878

**Pull request closed without merging**
